### ISSUE TITLE
[Cards] Error available class Xcode 16 beta 2  No type named 'terminate_handler' in namespace 'std' in Sentry

### ISSUE THREAD

**Issue by sakshibala-halodoc** [xendit/xendit-sdk-ios-src#81]
Description
Trying to compile the project with the latest version of Xendit using Xcode 16 beta 2. It works well with Xcode 15.4
We are using SPM for Xendit. 

Error
SwiftPackageManager/.build/checkouts/sentry-cocoa/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:59:13 No type named 'terminate_handler' in namespace 'std'

SwiftPackageManager/.build/checkouts/sentry-cocoa/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:194:47 No member named 'set_terminate' in namespace 'std'

SwiftPackageManager/.build/checkouts/sentry-cocoa/Sources/SentryCrash/Recording/Monitors/SentryCrashMonitor_CPPException.cpp:196:18 No type named 'set_terminate' in namespace 'std'

<img width="418" alt="Screenshot 2024-07-08 at 12 23 59 PM" src="https://github.com/xendit/xendit-sdk-ios-src/assets/72126135/042a227b-ab97-449b-ab4f-51e1d7a9854e">

**Comment by LF-XiaofeiShao** [comment]
This also happens in Xcode 16.0 beta 3 (16A5202i)

**Comment by LF-XiaofeiShao** [comment]
This also happens in Xcode 16.0 RC (16A242). 
Xcode 16 is expected to be officially released on September 16, please fix it quickly.

**Comment by LF-XiaofeiShao** [comment]
@adhiartaputra @duong-xendit @pandyaka @glyuck

**Comment by ignatiojuliant** [comment]
please just update to latest version release quickly

**Comment by azaky** [comment]
This is already fixed in the version [3.10.0](https://github.com/xendit/xendit-sdk-ios-src/releases/tag/3.10.0). However, note that the Sentry versions that fix this issue require minimum iOS 11, so we had to bump that as well. If your app need support for lower iOS versions, you still need to use SDK version 3.9.2 and XCode 15 at the latest.
